full pipeline

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,31 +1,44 @@
-name: Continuous Integration Flow
+# This is a basic workflow to help you get started with Actions
+
+name: Contionuos Integration Flow
 
 env:
+  # Use docker.io for Docker Hub if empty
   REGISTRY: ghcr.io
+  # github.repository as <account>/<repo>
   IMAGE_NAME: ${{ github.repository }}
 
+# Controls when the workflow will run
 on:
   push:
     branches: ["*"]
   pull_request:
     branches: ["main"]
 
+  # Allows you to run this workflow manually from the Actions tab
+  workflow_dispatch:
+
+# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  prepare:
+  # This workflow contains a single job called "build"
+  build:
     runs-on: ubuntu-latest
+    # runs-on: [self-hosted]
+    # The type of runner that the job will run on
+    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
+    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v3
-
-    - name: Install required packages
+    - name: getenv
       run: |
-        sudo apt-get update
-        sudo apt-get install -y curl jq git
+        env
 
+    # semantic-release
     - uses: actions/setup-node@v3
       with:
         node-version: 20
 
-    - name: Install semantic-release dependencies
+    - name: Install semantic releae dependencies
       run: |
         npm install -g semantic-release
         npm install -g @semantic-release/git @semantic-release/github @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/exec
@@ -36,7 +49,7 @@ jobs:
         calculatedSha=$(git rev-parse --short ${{ github.sha }})
         echo "short_sha=$calculatedSha" >> $GITHUB_OUTPUT
 
-    - name: Setup and execute semantic-release
+    - name: setup and execute semantic-release
       id: semantic_release_prep
       run: |
         cat <<EOF>> .releaserc.yml
@@ -47,32 +60,26 @@ jobs:
         plugins:
         - "@semantic-release/commit-analyzer"
         - "@semantic-release/release-notes-generator"
-        - "@semantic-release/changelog"
-        - "@semantic-release/git"
         - "@semantic-release/github"
         - - "@semantic-release/exec"
           - verifyReleaseCmd: echo \${nextRelease.version} > nextVersion
         EOF
-        semantic-release --dry-run --debug -r ${{ github.server_url }}/${{ github.repository }}.git
-        test -f nextVersion && echo "SRTAG=v$(cat nextVersion)" >> $GITHUB_OUTPUT || echo "SRTAG=${{ steps.vars.outputs.short_sha }}" >> $GITHUB_OUTPUT
-        echo $SRTAG
-        echo echo \${nextRelease.version}
+        semantic-release --dry-run -r ${{ github.server_url }}/${{ github.repository }}.git
+        test -f nextVersion && echo "SRTAG=v$(cat nextVersion)" >> ${GITHUB_OUTPUT} || echo "SRTAG=${{ steps.vars.outputs.short_sha }}" >> ${GITHUB_OUTPUT}
+        # echo $SRTAG
+        # cat nextVersion
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  build:
-    runs-on: ubuntu-latest
-    needs: prepare
-    services:
-      docker:
-        image: docker:20.10.16
-        options: --privileged
-    steps:
-    - uses: actions/checkout@v3
+    # build
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v2
 
     - name: Setup Docker buildx
       uses: docker/setup-buildx-action@v2
 
+    # Login against a Docker registry except on PR
+    # https://github.com/docker/login-action
     - name: Log into registry ${{ env.REGISTRY }}
       if: github.event_name != 'pull_request'
       uses: docker/login-action@v2
@@ -81,16 +88,37 @@ jobs:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
 
+    # add image caching 
+    - uses: satackey/action-docker-layer-caching@v0.0.11
+      # Ignore the failure of a step and avoid terminating the job.
+      continue-on-error: true
+      with:
+        key: foo-docker-cache-{hash}
+        restore-keys: |
+          foo-docker-cache-
+
+
+    # Extract metadata (tags, labels) for Docker
+    # https://github.com/docker/metadata-action
     - name: Extract Docker metadata
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
         tags: |
+          # set latest tag for master branch
           type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
           type=raw,value=latest-${{ github.ref_name }}
           type=raw,value=${{ steps.semantic_release_prep.outputs.SRTAG }}
+          
+    # For meta verification
+    - name: List Docker tag
+      run: echo "${{ steps.meta.outputs.tags }}"
 
+
+
+    # Build and push Docker image with Buildx (don't push on PR's)
+    # https://github.com/docker/build-push-action
     - name: Build and push Docker image
       id: build_n_push
       uses: docker/build-push-action@v4
@@ -101,17 +129,10 @@ jobs:
         labels: ${{ steps.meta.outputs.labels }}
         platforms: linux/amd64,linux/arm64
 
-  release:
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-    - uses: actions/checkout@v3
-
-    - name: Finalize and execute semantic-release
+    - name: setup and execute semantic-release
       id: semantic_release
       run: |
-        git config --global user.name "EvgeniTikal"
-        git config --global user.email "evgeni.sakhatsky@tikalk.com"
-        semantic-release --debug -r ${{ github.server_url }}/${{ github.repository }}.git
+        semantic-release -r ${{ github.server_url }}/${{ github.repository }}.git
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      if: steps.build_n_push.outputs.exit_code == 0
